### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by mrkvncnt** [mwdeshaw/Notable#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

Well done.

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments

Looks good.

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

`Users` may want a username or some other way of identifying them aside from email. Especially for reference in last_updated_by.

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

Check out the markdown cheat sheet for proper javascript notation. Otherwise good.

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

Great job, let's chat about `Tag` functionality before you get to that MVP. It's unlikely you'll need a `GET /api/notes/:note_id/tags` route since a `Tag` should come through the `Note` show page (unless you will be building out a show for a specific `Tag`.

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments

Good.

**Comment by mwdeshaw** [comment]
Thanks for opening this issue. Looking forward to your input!

**Comment by mrkvncnt** [comment]
No problem! See comments above. Any unchecked boxes should be addressed unless there is an (if needed). Over all this proposal is well written and your plan of action is sound. Let's set up a 1 <> 1 to discuss your work before you get started today.

**Comment by mwdeshaw** [comment]
Thanks for your feedback! A few questions. For usernames, the site does not use them, but one uses email to log in and register. However, one can optionally add a full name in their settings and this will take the place of email after login. Should I use some creative license and include a required username on register, for internal functions but not session functions? Next what is meant by the ui slice? I never got to that stage for any of the daily projects, so what is it exactly asking for/doing? Thank you  and looking forward to meeting later.

**Comment by mwdeshaw** [comment]
Deleted the GET /api/notes/:note_id/tags route, as I do not want a tags show page, but for tags for a specific note to show up. We will discuss before I begin that feature. I also reformatted the sample state to match the rubric. Finally for ui state, it appears that Evernote does not have any loading screens or icons from my investigation, so I will leave it out of the state for now. However, I read up how to implement it, so I am ready if a loading screen comes up in the process of my implementation, or as a little finishing touch right before production. Thanks!
