### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by mrkvncnt** [mwdeshaw/Notable#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by mwdeshaw** [comment]
The only thing I am missing is putting the demo user on Heroku. Perhaps we can address that tomorrow? Thanks!
